#pragma config(Sensor, in7,    gyro,           sensorGyro)
#pragma config(Sensor, in8,    Pexpander,      sensorAnalog)
#pragma config(Sensor, dgtl1,  claw1,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  Renc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  push,           sensorDigitalOut)
#pragma config(Sensor, dgtl5,  jumper,           sensorDigitalIn)
#pragma config(Sensor, dgtl9,  claw2,          sensorDigitalOut)
#pragma config(Sensor, dgtl10, limit,          sensorTouch)
#pragma config(Sensor, dgtl11, Lenc,           sensorQuadEncoder)
#pragma config(Motor,  port1,           RM,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           R1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           R2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           MG1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           MG2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           L1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           L2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LM,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

////    Jason Becker    ////
//// VCAT Robotics 2018 ////
#pragma DebuggerWindows("debugStream")
#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "CompensationCheck.c";
/////////////////////// Mobile Goal Class//////////////////////////////////
typedef struct
{
	int val;
}MOGO;
MOGO mobi;
/////////////////////// Mobile Goal Class//////////////////////////////////
int dr, dl, mg, c, p;
#include "Tasks.c"

//VVVVVVVVVVVVVVVVVVVVVV Voltage Check Class Structure VVVVVVVVVVVVVVVV
typedef struct
{
	float mult;
}TVoltage;
TVoltage pr;
TVoltage se;
//VVVVVVVVVVVVVVVVVVVVVV Voltage Check Class Structure VVVVVVVVVVVVVVVV
#include "VexIncludes.c"
#include "functions.c"


void pre_auton()
{SensorType[in7] = sensorNone;
wait1Msec(1000);
SensorType[in7] = sensorGyro;
wait1Msec(2000);
	bStopTasksBetweenModes = true;

}



task autonomous()
{
	//!!!!!!!!!! CHECK VOLTAGES !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	pr.mult=PCheck(nImmediateBatteryLevel/1000.0);
	se.mult=SCheck(SensorValue[Pexpander]/280.0);
	//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#include "Auto.c";
	while(1){}
}



task usercontrol()
{
	startTask(runD);
	if (jumper == 1)
	{
		while (1)
		{
			writeDebugStreamLine("D(%d,%d,%d,%d,%d);", dr, dl, mg, c, p);
			D(dr, dl, mg, c, p);

		}
	}
	else
	{
	}
	while (1)
	{
		D(dr, dl, mg, c, p);
	}
}
}
