#pragma config(Sensor, in8,    BackUpBattery,  sensorAnalog)
#pragma config(Sensor, dgtl1,  enc,            sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  claw,           sensorDigitalOut)
#pragma config(Sensor, dgtl4,  limit,          sensorTouch)
#pragma config(Sensor, dgtl8,  Climit,         sensorTouch)
#pragma config(Sensor, dgtl10, IR,             sensorDigitalIn)
#pragma config(Sensor, dgtl11, sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           RM,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           L1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           MG,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightArm1,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightArm2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftArm2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ClawM,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           R1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LM,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//~~~~~~~~ MAIN.C V3 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#pragma DebuggerWindows("debugStream")
#include"CompensationCheck.c";
#include "Functions.c";
task main()
{clearDebugStream();
	//!!!!!!!!!! CHECK VOLTAGES !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	SensorValue[enc]=0;
	float pm, sm/*,Pin*/; //primary multiplier, secondary multiplier
	float MainBattery=nImmediateBatteryLevel; //Main Battery input
	float Batt=MainBattery/1000; //Division by 1000 to get true voltage value of battery
	pm=PCheck(Batt); //Create Multiplier Based On Battery Voltage
	float SecondaryBattery=SensorValue[BackUpBattery]; //Main Battery input
	float Batt2=SecondaryBattery/280.0; //Division by 1000 to get true voltage value of battery
	sm=SCheck(Batt2); //Create Multiplier Based On Battery Voltage
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//#include "DOTHETHING.c";
		while (1)
		{
			//#include "DriverControl.c";
	#include "JuanDriverControl.c";
	}
}
