#pragma config(Sensor, in1,    gyro,           sensorLineFollower)
#pragma config(Sensor, in2,    fourPOT,        sensorPotentiometer)
#pragma config(Sensor, in8,    BackUpBattery,  sensorAnalog)
#pragma config(Sensor, dgtl1,  claw,           sensorDigitalOut)
#pragma config(Sensor, dgtl2,  IR,             sensorDigitalIn)
#pragma config(Sensor, dgtl3,  liftlimit,      sensorTouch)
#pragma config(Motor,  port1,           MG,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RSlideFr,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RSlideBa,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           RDriveMid,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           ABpower,       tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           LSlideFr,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LSlideBa,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LDriveMid,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port9,           CDpower,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          FourBar,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(45)
#pragma userControlDuration(75)

#define DEBUG 1
///////////////////////////BEGIN INCLUDED FILES
int alliance = 4;
int autonomousN = 5;
#include "vex.c"
//#include "RedAuto1.c"
//#include "RedAuto2.c"
//#include "RedAuto3.c"
//#include "BlueAuto1.c"
//#include "BlueAuto2.c"
//#include "BlueAuto3.c"
//#include "BlueAuto4.c"
//#include "BlueAuto5.c"
#include "Functions.c"


void pre_auton()
{
	//	bStopTasksBetweenModes = true;
	//#include "PreAuto.c";
}



task autonomous()
{
#include "Auto.c";
}


task usercontrol()
{ stopTask(autonomous);

	while (true)
	{
#include "DriverControl.c";
	}
}
