#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in8,    BackUpBattery,  sensorAnalog)
#pragma config(Sensor, dgtl1,  enc,            sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  claw,           sensorDigitalOut)
#pragma config(Sensor, dgtl4,  limit,          sensorTouch)
#pragma config(Sensor, dgtl5,  Lenc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  Renc,           sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  Climit,         sensorTouch)
#pragma config(Sensor, dgtl10, IR,             sensorDigitalIn)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           RM,            tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           leftArm,       tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           MG,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           L1,            tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           L2,            tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           R1,            tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port7,           R2,            tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           ClawM,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightArm,      tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          LM,            tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//~~~~~~~~ MAIN.C V3 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#pragma DebuggerWindows("debugStream")
#include"CompensationCheck.c";
#include "Functions.c";
task main()
{clearDebugStream();
	SensorValue[enc]=0;
	//##########   RECORD  ####################################################
	int record=0;
	//########################################################################
	//!!!!!!!!!! CHECK VOLTAGES !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	float pm, sm/*,Pin*/; //primary multiplier, secondary multiplier
	float MainBattery=nImmediateBatteryLevel; //Main Battery input
	float Batt=MainBattery/1000; //Division by 1000 to get true voltage value of battery
	pm=PCheck(Batt); //Create Multiplier Based On Battery Voltage
	float SecondaryBattery=SensorValue[BackUpBattery]; //Main Battery input
	float Batt2=SecondaryBattery/280.0; //Division by 1000 to get true voltage value of battery
	sm=SCheck(Batt2); //Create Multiplier Based On Battery Voltage
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//#include "DOTHETHING.c";
		while (1)
		{
			//#include "Rahemi.c";
			//#include "DriverControl.c";
	#include "JuanDriverControl.c";
//#include "Spin.c";
	}
}
