#pragma config(Sensor, dgtl12, piston,         sensorDigitalOut)
#pragma config(Motor,  port2,           frontRight,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           backRight,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           liftRight1,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           liftRight2,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           liftLeft1,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           liftLeft2,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		//motor[frontRight] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
		//motor[backRight] =  vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
		//motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
		//motor[backLeft] =  vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];

		motor[frontLeft] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
		motor[frontRight] = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
		motor[backLeft] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
		motor[backRight]= vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];

		if (vexRT[Btn5U]==1)
		{motor[liftLeft1]=127;
			motor[liftLeft2]=127;
			motor[liftRight1]=127;
			motor[liftRight2]=127;
		}
		else if (vexRT[Btn5D]==1)
		{motor[liftLeft1]=-127;
			motor[liftLeft2]=-127;
			motor[liftRight1]=-127;
			motor[liftRight2]=-127;
		}
		else if(vexRT[Btn6U]==1)
		{motor[liftLeft1]=10;
			motor[liftLeft2]=10;
			motor[liftRight1]=10;
			motor[liftRight2]=10;
		}
		else{motor[liftLeft1]=0;
			motor[liftLeft2]=0;
			motor[liftRight1]=0;
			motor[liftRight2]=0;}

		if(vexRT[Btn6D]==1)
		{SensorValue[piston]=1;
		}
		else
		{SensorValue[piston]=0;
		}
	}
}
